version: "3"
services:
  # MySQL
  db:
    image: mysql:5.7.30
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_sample
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  # node.js
  nodejs:
    build: ./nodejs
    container_name: nodejs
    image: marumaruji/nodejs:12
    #    environment:
    #      TZ: 'Asia/Tokyo'
    volumes:
      - ./src:/opt/src
    ports:
      - 3000:3000
    depends_on:
      - db